apiVersion: v1
kind: Service # 定义Kubernetes资源的类型为Service
metadata:
  name: app-web-service # 定义资源的名称
spec:
  selector: # 指定对应的Pod
    app: aspnetapp-demo # 指定Pod的标签为demo-web
  type: NodePort # 指定Service的类型，在这里使用NodePort来对外访问
  ports:
  - protocol: TCP # 协议类型
    nodePort: 31000 #物理主机端口
    port: 80 # 指定Service访问的端口
    targetPort: 80 # 指定Service转发请求的端口