apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-app
spec:
  containers:
    - name: aspnetapp
      image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
      ports:
        - containerPort: 80 # 定义容器监听的端口
